version: "2.4"

x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
  hello-jetson:
    image: nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf2.3-py3
    runtime: nvidia
    cpus: 0.8
    mem_limit: 100m
    memswap_limit: 200m
    restart: on-failure
    logging:
      <<: *default-log
    command: 
      - python3
      - -c
      - "import tensorflow as tf;print(tf.config.list_physical_devices('GPU'));"
 