version: "2.4"

x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
  hello-video:
    image: hsz1273327/hello-video:0.0.1
    cpus: 0.8
    mem_limit: 100m
    memswap_limit: 200m
    restart: on-failure
    logging:
      <<: *default-log
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
 