version: "2.4"

x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
  iperf3-serv:
    image: hsz1273327/iperf3:3.7
    logging:
      <<: *default-log
    ports:
      - "5201:5201"
    command: ["-s"]

  iperf3-test:
    image: hsz1273327/iperf3:3.7
    depends_on:
      - iperf3-serv
    logging:
      <<: *default-log
    command: ["-c", "iperf3-serv","-d","--get-server-output"]
   
    