version: "2.4"
x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
  file_watcher:
    image: hsz1273327/standalone_colume_nfs:latest
    logging:
      <<: *default-log
    mem_limit: 100m
    memswap_limit: 200m
    restart: on-failure
    volumes:
      - "nfssharev3:/data"
volumes:
  nfssharev3:
    external: true