version: "2.4"

x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
  file_watcher:
    build:
      context: ./app
      dockerfile: Dockerfile_test
    image: hsz1273327/standalone_colume_nfs:0.0.0
    cpus: 0.8
    mem_limit: 100m
    memswap_limit: 200m
    restart: on-failure
    logging:
      <<: *default-log
    volumes:
      - "mynfs:/data"
volumes:
  mynfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.31.212,rw,nfsvers=4,async"
      device: ":/volume2/docker_share"