version: "3.7"
services:
  proxy:
    image: nginx
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==RaspPiNode1"
    networks:
      - mynetwork
    configs:
      - source: nginx-for-host
        target: /etc/nginx/nginx.conf

  helloworld:
    image: hsz1273327/hellodocker-go:0.0.0
    networks:
      - mynetwork
    deploy:
      mode: global
    
  test_helloworld:
    image: hsz1273327/ab:0.0.0
    command: 
      - "-c"
      - "25"
      - "-n"
      - "10000"
      - http://192.168.31.41:5001/
configs:
  nginx-for-host:
    external: true
networks:
  mynetwork:
    external: true
    name: host
