version: "3.7"
services:
  proxy:
    image: nginx
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==RaspPiNode1"
    networks:
      - mynetwork
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf

  helloworld:
    image: hsz1273327/hellodocker-go:0.0.0
    networks:
      - mynetwork
    deploy:
      mode: global
    
configs:
  nginx-conf:
    external: true
networks:
  mynetwork:
    external: true
    name: host
