FROM python:3.8.7-alpine as build_bin
ADD pip.conf /etc/pip.conf
RUN pip --no-cache-dir install --upgrade pip
WORKDIR /code
RUN mkdir /code/app
ADD requirements.txt /code/requirements.txt
RUN python -m pip --no-cache-dir install -r requirements.txt --target app
RUN rm -rf app/*.dist-info
ADD app/__main__.py /code/app/__main__.py
RUN python -m zipapp -p "/usr/bin/env python3" app

FROM python:3.8.7-alpine as build_img
WORKDIR /code
COPY --from=build_bin /code/app/app.pyz /code
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl","-f","http://localhost:5000/ping" ]
CMD ["python" ,"app.pyz"]